# Site settings
title: Lpc-Win32's Blog
SEOTitle: Lpc-Win32博客 | Lpc-Win32 Blog
header-img: img/home-bg.jpg
email: 312041933@qq.com
description: ""
keyword: "lpc-win32,Linux,cpp,c++11,c,kernel,libttzhu"
#url: "https://lpc-win32.github.io"              # your host, for absolute URL
#baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     lpc-win32
zhihu_username:     lpc-win32
github_username:    lpc-win32
#twitter_username:  lpc-win32
#facebook_username:  lpc-win32


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
    
# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: lpc-win32
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: lpc-win32.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "学习、分享与沉淀"
sidebar-avatar: /img/avatar-lpc.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                    # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Developer_google",
        href: "https://developer.google.com"
    },{
        title: "GitHub",
        href: "https://www.github.com"
    },{
        title: "OPEN SOURCE CHINA",
        href: "http://www.oschina.net/"
    }
]
